### ISSUE TITLE
Content on homepage.

### ISSUE THREAD

**Issue by zodvik** [vdugar/Seinfeld-Calendar#2]
Fill the content on homepage.
How to use guide.
contact information.

**Comment by vdugar** [comment]
How to-> Should be a simple graphic-based popup
Homepage content-> Lemme think
Contact information-> Depends on our hosting options, I guess

_Remind people to set as homepage_

**Comment by zodvik** [comment]
instead of how-to, we can have a guided demo!
no data will get saved in db but jquery will show the changes until the page is refreshed.
