### ISSUE TITLE
Calendar design

### ISSUE THREAD

**Issue by zodvik** [vdugar/Seinfeld-Calendar#3]

**Comment by vdugar** [comment]
1. Make start date more prominent (thicker border, I guess)
2. Cool '?' graphics for the editable dates

**Comment by zodvik** [comment]
thicker border will displace the other boxes. it is counted in width of the box

**Comment by vdugar** [comment]
Some other colour or graphic, then.

**Comment by zodvik** [comment]
green colored play button?

On Wed, Jun 1, 2011 at 1:20 PM, vdugar
reply@reply.github.com
wrote:

> Some other colour or graphic, then.
> 
> On Wed, Jun 1, 2011 at 1:16 PM, nrbafna <

**Comment by vdugar** [comment]
haan....chalega

**Comment by zodvik** [comment]
got a break into multiple post thing... it is called as many times as
a user clicked on 'upto no good button' before clicking 'i have done'

On Wed, Jun 1, 2011 at 1:29 PM, vdugar
reply@reply.github.com
wrote:

**Comment by zodvik** [comment]
and a working jugaad fix.
